Translatable option strings
emlys/invest pull request #1
Opened 2021-12-04 00:11 UTC by emlys

2021-12-07 23:03 UTC, phargogh requested changes
Hey @emlys I saw [your comment over in the InVEST PR](https://github.com/natcap/invest/pull/645#issuecomment-987210601) and thought I'd take a look, so I'm sorry if I jumped the gun on this!  Just had a couple small comments but overall the changes look good to me.

2021-12-07 23:03 UTC, phargogh commented on src/natcap/invest/crop_production_percentile.py
> +                        crop: {"description": crop} for crop in [
Nice use of a comprehension here!  Is this still a `TODO`, or does the comprehension address it?

2021-12-07 23:03 UTC, phargogh commented on HISTORY.rst
> +      ``australia``, ``global``.
These are just with the options presented in the UI, right?  They won't change the `args` option itself, right?  If so, that might be helpful to include here in the HISTORY.

2021-12-07 23:03 UTC, phargogh commented on src/natcap/invest/recreation/recmodel_client.py
> +                    "AOI grid cell.")}
I think I remember you mentioning that some models (and this looks to be an example) use underscores to separate words ... should these also have a display name set?

2021-12-08 19:08 UTC, emlys commented on src/natcap/invest/recreation/recmodel_client.py
> +                    "AOI grid cell.")}
These should not, because they're column headers in a table, not dropdown options

2021-12-08 19:16 UTC, emlys commented on src/natcap/invest/crop_production_percentile.py
> +                        crop: {"description": crop} for crop in [
This is still a TODO, since some of the names have abbreviations or suffixes that need to be defined (natcap/invest#614).

2021-12-08 19:47 UTC, emlys commented on HISTORY.rst
> +      ``australia``, ``global``.
I did change the actual `args` options here to take advantage of having a separate option key vs. display name. For example, the UI dropdown will show "West Coast of North America and Hawaii" as before, but the arg value will be `"westcoast"`, just so we're not using those long phrases as keys in the model code.

I tried to clarify this in the history note. Let me know what you think!

2021-12-08 19:49 UTC, emlys commented
Thanks @phargogh! Yes, this was ready for review. For some reason I couldn't request your review on it, maybe some setting on my fork? Anyways this is ready again.

2021-12-11 01:01 UTC, phargogh commented on src/natcap/invest/recreation/recmodel_client.py
> +                    "AOI grid cell.")}
Ah right.  Thanks!

2021-12-11 01:02 UTC, phargogh commented on HISTORY.rst
> +      ``australia``, ``global``.
The updated history notes look great!  I really like how it clarifies who should take note of the change.

2021-12-11 01:07 UTC, phargogh approved these changes
Ok great!  Thanks for the updates.  I see that there are a couple of build failures @emlys where I think maybe the `investspec` portion of the UG aren't quite lining up with the updated `ARGS_SPEC` for Wave Energy, but that can be resolved back in https://github.com/natcap/invest/pull/645 so I'll merge this one!

2021-12-11 01:08 UTC, phargogh commented
Ha, of course I can't merge the branch into your branch on your fork!  So I guess I'll have to leave that to you to do @emlys !

But also I wanted to call out the arg change in the UG, which'll need to be updated over there at some point

2021-12-11 01:59 UTC, emlys commented
Oh, right! I just updated the user's guide.

2021-12-11 01:59 UTC, merged